### ISSUE TITLE
Improve how translations are done

### ISSUE THREAD

**Issue by reinink** [thephpleague/thephpleague.github.io#21]
I'm quickly realizing that managing these sites, and the design changes, is going to become a bit of a nightmare. Just consider the Spanish translation (http://es.thephpleague.com/), which has the old design of the site. Bringing it up to speed is going to be a pain.

What if we had a `_data\local.yml` which housed all the translation info in it. Meaning all the sites would be identical, except this file. When a translation needs to be done, it simply means updating one file as well. Something like this:

``` yaml
name: The League of Extraordinary Packages
intro: The League of Extraordinary Packages is a group of developers who have banded together to build solid, well tested PHP packages using modern coding standards.
features:
    - feature_1: We comply to the standards of the PHP-FIG.
    - feature_2: We adhere to the best-practices put forward by PHP The "Right" Way.
    - feature_3: We distribute code via Packagist and Composer.
packages:
    - title: Our Packages
    - project_name: Name
    - project_description: description
    - project_lead: project Lead
    - project_work_in_progress: a work-in-progress package
quailty:
    - title: Our Definition Of Quality
    - introduction: Ask 100 developers what defines an awesome PHP package and you’ll get a lot of different answers. That also sounds like a really long and boring task, so we’ve come up with a list of rules that we think make a package awesome.
```
